"""add fee_amount to transfers and payments

Revision ID: 564c3c041553
Revises: 6fc808082003
Create Date: 2026-07-25 11:30:46.035913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564c3c041553'
down_revision: Union[str, Sequence[str], None] = '6fc808082003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('fee_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('transfers', sa.Column('fee_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'fee_amount')
    op.drop_column('payments', 'fee_amount')
    # ### end Alembic commands ###
